eze:
  network:
    host: 0.0.0.0
    port: 26500
  data:
    directory: /Users/lizhi/Desktop/eze/
    logSegmentSize: 10MB
    snapshotPeriod: 5m
  exporters:
    elasticsearch:
      class-name: io.camunda.zeebe.exporter.ElasticsearchExporter
      args:
        url: http://localhost:9200


